version: '3'

services:
  mysql: 
    image: mysql:8.0.31
    container_name: laravel-mysql
    environment:
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"   
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci   
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmiin:
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: laravel-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "8080:80"
    depends_on:
      - mysql
  php:
    build: ./docker/php
    container_name: laravel-php
    volumes:
      - ./${APP_NAME}:/var/www/html
    ports:
      - "8000:80"
